apiVersion: v1
appVersion: 0.42.1
description: kube-prometheus collects Kubernetes manifests to provide easy to operate end-to-end Kubernetes cluster monitoring with Prometheus using the Prometheus Operator.
name: kube-prometheus
version: 2.2.1
keywords:
  - prometheus
  - alertmanager
  - operator
  - monitoring
home: https://github.com/bitnami/charts/tree/master/bitnami/kube-prometheus
icon: https://bitnami.com/assets/stacks/prometheus-operator/img/prometheus-operator-stack-220x234.png
sources:
  - https://github.com/bitnami/bitnami-docker-prometheus-operator
  - https://github.com/bitnami/bitnami-docker-prometheus
  - https://github.com/bitnami/bitnami-docker-alertmanager
  - https://github.com/prometheus-operator/kube-prometheus
maintainers:
  - name: Bitnami
    email: containers@bitnami.com
engine: gotpl
annotations:
  category: Analytics
